extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 2s
    limit_mib: 512
    spike_limit_mib: 128

  batch:
    send_batch_size: 1024
    timeout: 5s

  resource:
    attributes:
      - action: upsert
        key: deployment.environment
        value: local
      - action: upsert
        key: service.namespace
        value: energy-demand-forecasting

exporters:
  # Traces -> Tempo
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Metrics -> Prometheus scrapes this exporter endpoint (pipeline metrics)
  prometheus:
    endpoint: 0.0.0.0:8889

  # Logs -> Loki via OTLP/HTTP
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

service:
  extensions: [health_check]

  # Collector's OWN internal telemetry metrics endpoint (Prometheus pull)
  telemetry:
    logs:
      level: info
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/tempo]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp/logs]